"""Evidence-grounded progress-report and plan-coaching Harness skills.

Progress reports are generated by a real model-backed agent.  Deterministic
code still owns source selection, validation and rendering so the model cannot
turn workflow logs or missing fields into research facts.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from typing import Any
from urllib.parse import urlparse

from pydantic import BaseModel, Field, ValidationError
from sqlalchemy.orm import Session

from backend.db.repositories import AgentRunRepository
from backend.db.types import RunStatus, WorkflowName
from backend.harness.contracts import RunCreate, RunCreated
from backend.integrations.llm.openai_compatible import OpenAICompatibleChatModelAdapter
from backend.services.providers import chat_provider_from_settings
from backend.settings import get_settings
from backend.tools.context import tool_session


class ReportFinding(BaseModel):
    title: str = Field(min_length=1, max_length=120)
    fact: str = Field(min_length=1, max_length=700)
    significance: str = Field(min_length=1, max_length=500)
    evidence_refs: list[str] = Field(default_factory=list)


class ReportBlocker(BaseModel):
    issue: str = Field(min_length=1, max_length=300)
    impact: str = Field(min_length=1, max_length=400)
    proposed_resolution: str = Field(min_length=1, max_length=500)
    evidence_refs: list[str] = Field(default_factory=list)


class ReportAction(BaseModel):
    action: str = Field(min_length=1, max_length=240)
    rationale: str = Field(min_length=1, max_length=400)
    deliverable: str = Field(min_length=1, max_length=300)
    acceptance_criteria: list[str] = Field(min_length=1, max_length=4)
    priority: str = "medium"
    target_date: str | None = None
    evidence_refs: list[str] = Field(default_factory=list)


class ProgressReportDraft(BaseModel):
    executive_summary: str = Field(min_length=40, max_length=1200)
    progress_assessment: str = Field(min_length=20, max_length=1000)
    completed_work: list[ReportFinding] = Field(default_factory=list)
    work_in_progress: list[ReportFinding] = Field(default_factory=list)
    blockers: list[ReportBlocker] = Field(default_factory=list)
    discussion_insights: list[ReportFinding] = Field(default_factory=list)
    next_actions: list[ReportAction] = Field(min_length=1, max_length=6)
    risks: list[str] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)


_RUNTIME_LINE = re.compile(
    r"^(?:WORKFLOW_|Harness\s|已收到需求|意图已确认|正在规划|计划已生成|"
    r"开始领域分析|领域判断完成|导师研究\s*Agent|查询约束已冻结|"
    r"检索管理器|开始执行检索器|检索器执行完成|召回完成|导师研究完成|"
    r"匹配\s*Agent|匹配完成|独立审核|审核通过|本轮多智能体任务完成)",
    flags=re.IGNORECASE,
)


def queue_progress_report(request: RunCreate, session: Session) -> RunCreated:
    """Persist immediately; the HTTP request never waits on the report model."""

    period = request.context.report_period or "weekly"
    title = _report_title(period)
    run = AgentRunRepository(session).create(
        WorkflowName.progress_report.value,
        status=RunStatus.pending.value,
        input_json={
            "message": request.message,
            "metadata": {
                "harness_skill_id": "progress_report",
                "period_type": period,
            },
        },
        output_json={
            "review_status": "PENDING",
            "evidence_refs": [],
            "artifact": {
                "type": "progress_report",
                "period_type": period,
                "title": title,
                "markdown": "",
                "generation": {"agent": "progress_report_agent", "status": "queued"},
            },
        },
    )
    session.commit()
    return RunCreated(
        run_id=str(run.id),
        skill_id="progress_report",
        status=RunStatus.pending.value,
        review_status="PENDING",
        artifact=run.output_json["artifact"],
    )


def execute_progress_report(run_id: int, request_payload: dict[str, Any]) -> None:
    request = RunCreate.model_validate(request_payload)
    with tool_session() as session:
        start_progress_report(request, session, run_id=run_id)


def start_progress_report(
    request: RunCreate,
    session: Session,
    *,
    run_id: int | None = None,
) -> RunCreated:
    context = request.context
    period = context.report_period or "weekly"
    events = [item for item in context.progress_events if isinstance(item, dict)]
    plans = [item for item in context.plans if isinstance(item, dict)]
    chats = [item for item in context.chat_summary if isinstance(item, dict)]
    growth = context.growth or {}
    completed = [item for item in plans if item.get("status") == "done"]
    pending = [item for item in plans if item.get("status") in {"todo", "doing"}]
    evidence_refs = list(dict.fromkeys(
        str(ref)
        for item in events
        for ref in (item.get("evidence_refs") or [])
        if str(ref)
    ))
    evidence_refs = list(
        dict.fromkeys([*evidence_refs, *_collect_evidence_refs(growth)])
    )
    metrics = {
        "activity_events": len(events),
        "dialogue_turns": len(chats),
        "completed_plans": len(completed),
        "pending_plans": len(pending),
        "matched_mentors": len(growth.get("matched_mentors") or []),
        "read_papers": len(growth.get("read_papers") or []),
    }
    title = _report_title(period)
    snapshot, source_refs = _report_snapshot(events, plans, chats, growth)
    evidence_refs = list(dict.fromkeys([*evidence_refs, *source_refs]))
    try:
        draft, generation = _generate_report_draft(
            period=period,
            title=title,
            metrics=metrics,
            snapshot=snapshot,
            allowed_evidence_refs=evidence_refs,
        )
        draft = _restrict_evidence_refs(draft, set(evidence_refs))
        markdown = _render_progress_markdown(title, period, metrics, draft)
        failed_checks = _review_report(markdown, draft)
    except Exception as exc:  # noqa: BLE001 - persist an auditable agent failure
        artifact = {
            "type": "progress_report",
            "period_type": period,
            "title": title,
            "markdown": "",
            "metrics": metrics,
            "evidence_refs": evidence_refs,
            "generated_at": datetime.now(UTC).isoformat(),
            "generation": {
                "agent": "progress_report_agent",
                "status": "failed",
                "config_source": "environment_chat_config",
            },
            "failed_checks": ["model_generation_failed"],
            "error": f"{type(exc).__name__}: {exc}",
        }
        return _persist_progress(
            session,
            request,
            artifact,
            evidence_refs,
            status=RunStatus.failed.value,
            review_status="FAILED",
            run_id=run_id,
        )

    review_status = "PASS" if not failed_checks else "REVISE"
    artifact = {
        "type": "progress_report",
        "period_type": period,
        "title": title,
        "markdown": markdown,
        "metrics": metrics,
        "evidence_refs": evidence_refs,
        "generated_at": datetime.now(UTC).isoformat(),
        "generation": generation,
        "failed_checks": failed_checks,
        "limitations": ["报告只汇总已记录活动；未记录的线下进展保持 unknown。"],
    }
    return _persist_progress(
        session,
        request,
        artifact,
        evidence_refs,
        status=RunStatus.succeeded.value,
        review_status=review_status,
        run_id=run_id,
    )


def start_plan_coach(request: RunCreate, session: Session) -> RunCreated:
    plans = [item for item in request.context.plans if isinstance(item, dict)]
    growth = request.context.growth or {}
    pending_research = [
        item for item in growth.get("research_tasks") or []
        if isinstance(item, dict) and item.get("status") in {"pending", "in_progress"}
    ]
    suggestions: list[dict[str, Any]] = []
    if len([item for item in plans if item.get("status") in {"todo", "doing"}]) > 5:
        suggestions.append({"kind": "workload", "text": "当前开放计划超过 5 项，建议先冻结低优先级任务，保持每周最多 3 个核心交付。"})
    if any(not item.get("due_at") for item in plans if item.get("status") != "done"):
        suggestions.append({"kind": "deadline", "text": "部分计划缺少截止时间；建议补充可验证的日期与验收标准。"})
    for task in pending_research[:3]:
        suggestions.append({
            "kind": "research_task",
            "text": f"把研究任务“{task.get('title') or task.get('id')}”拆成一次 60–90 分钟的论文证据阅读与一次结论整理。",
            "source_task_id": task.get("id"),
            "evidence_refs": task.get("evidence_refs") or [],
        })
    if not suggestions:
        suggestions.append({"kind": "focus", "text": "当前计划负荷可控；优先完成最早到期且有明确验收标准的一项。"})
    evidence_refs = list(dict.fromkeys(
        str(ref)
        for item in suggestions
        for ref in (item.get("evidence_refs") or [])
        if str(ref)
    ))
    artifact = {
        "type": "plan_coach",
        "suggestions": suggestions,
        "evidence_refs": evidence_refs,
        "generated_at": datetime.now(UTC).isoformat(),
    }
    return _persist(session, request, WorkflowName.plan_coach.value, "plan_coach", artifact, evidence_refs)


def productivity_result(run_id: int, session: Session, workflow: str, skill_id: str) -> RunCreated:
    from backend.db.models import AgentRun

    run = session.get(AgentRun, run_id)
    if run is None or run.workflow != workflow:
        raise ValueError(f"{skill_id} AgentRun not found")
    output = dict(run.output_json or {})
    return RunCreated(
        run_id=str(run.id), skill_id=skill_id, status=run.status,
        review_status=str(output.get("review_status") or "PENDING"),
        evidence_refs=list(output.get("evidence_refs") or []), artifact=output.get("artifact"),
    )


def _report_title(period: str) -> str:
    return {
        "daily": "科研日报",
        "weekly": "科研周报",
        "monthly": "科研月报",
    }.get(period, "科研进展报告")


def _report_snapshot(
    events: list[dict[str, Any]],
    plans: list[dict[str, Any]],
    chats: list[dict[str, Any]],
    growth: dict[str, Any],
) -> tuple[dict[str, Any], list[str]]:
    """Build a compact source packet instead of sending raw workflow dumps."""

    refs: list[str] = []
    event_rows: list[dict[str, Any]] = []
    ordered_events = sorted(events, key=lambda item: str(item.get("created_at") or ""))
    # Reports need representative facts, not every workflow heartbeat.  Keeping
    # this packet compact materially reduces first-token latency on the shared
    # CHATAGENT endpoint while preserving recent, auditable evidence.
    for index, item in enumerate(ordered_events[-20:], start=1):
        object_type = str(item.get("object_type") or "activity")
        object_id = str(item.get("object_id") or index)
        source_ref = f"activity:{object_type}:{object_id}"
        refs.append(source_ref)
        event_rows.append(
            {
                "source_ref": source_ref,
                "created_at": item.get("created_at"),
                "verb": item.get("verb"),
                "object_type": object_type,
                "object_id": object_id,
                "result": _compact_value(item.get("result") or {}),
                "evidence_refs": list(item.get("evidence_refs") or [])[:6],
            }
        )

    plan_rows: list[dict[str, Any]] = []
    for index, item in enumerate(plans[:12], start=1):
        source_ref = f"plan:{item.get('id') or index}"
        refs.append(source_ref)
        plan_rows.append(
            {
                "source_ref": source_ref,
                "title": str(item.get("title") or "")[:240],
                "description": str(item.get("description") or "")[:500],
                "status": item.get("status"),
                "priority": item.get("priority"),
                "due_at": item.get("due_at"),
                "estimated_minutes": item.get("estimated_minutes"),
                "actual_minutes": item.get("actual_minutes"),
                "completed_at": item.get("completed_at"),
            }
        )

    chat_rows: list[dict[str, Any]] = []
    for index, item in enumerate(chats[-12:], start=1):
        content = _clean_chat_content(str(item.get("content") or ""))
        if not content:
            continue
        source_ref = f"chat:{str(item.get('created_at') or index).replace(' ', 'T')}"
        refs.append(source_ref)
        chat_rows.append(
            {
                "source_ref": source_ref,
                "role": item.get("role"),
                "created_at": item.get("created_at"),
                "content": content[:700],
            }
        )

    growth_rows = {
        "directions": _compact_value(growth.get("directions") or []),
        "matched_mentors": _compact_value(growth.get("matched_mentors") or []),
        "read_papers": _compact_value(growth.get("read_papers") or []),
        "research_tasks": _compact_value(growth.get("research_tasks") or []),
        "verified_experiences": _compact_value(
            growth.get("verified_experiences") or []
        ),
    }
    return {
        "activity_records": event_rows,
        "plan_records": plan_rows,
        "dialogue_records": chat_rows,
        "growth_state": growth_rows,
    }, list(dict.fromkeys(refs))


def _generate_report_draft(
    *,
    period: str,
    title: str,
    metrics: dict[str, int],
    snapshot: dict[str, Any],
    allowed_evidence_refs: list[str],
) -> tuple[ProgressReportDraft, dict[str, Any]]:
    settings = get_settings()
    provider = chat_provider_from_settings(settings).model_copy(deep=True)
    provider.settings = {
        **provider.settings,
        "max_tokens": min(settings.chat_max_tokens, 2200),
        "timeout": min(float(provider.settings.get("timeout") or 60), 60),
        "max_retries": 0,
        "response_format": {"type": "json_object"},
    }
    period_name = {"daily": "本日", "weekly": "本周", "monthly": "本月"}.get(
        period, "本周期"
    )
    system = f"""
你是科研进展报告 Agent。请按照正式组会汇报的严谨度分析{period_name}记录，而不是复述数据库日志。

硬约束：
1. 只能使用 input_snapshot 中的记录；未记录的事实必须写入 missing_information，禁止补写。
2. WORKFLOW、Agent、检索开始/完成等运行日志不是科研成果。只有计划完成、已审核产物、论文阅读、研究结论或用户明确陈述才能进入 completed_work。
3. 每个事实、阻塞和建议尽量引用 allowed_evidence_refs；不得创造列表外的引用。
4. 区分“做了什么”“得到什么结果”“科研意义是什么”。没有结果时明确写“尚无可核验结论”。
5. 下一步必须具体到交付物和验收标准，避免“继续努力、加强学习”等空话。
6. 输出中文；语气适合实验室组会，简洁但有分析，不输出思维链。
7. 只返回符合 required_json_schema 的 JSON 对象，不要 Markdown 代码围栏。
""".strip()
    payload = {
        "report_title": title,
        "period_type": period,
        "metrics": metrics,
        "allowed_evidence_refs": allowed_evidence_refs,
        "input_snapshot": snapshot,
        "required_json_schema": ProgressReportDraft.model_json_schema(),
    }
    raw = OpenAICompatibleChatModelAdapter().generate_text(
        provider,
        [
            {"role": "system", "content": system},
            {
                "role": "user",
                "content": "请生成结构化科研进展报告。\n" + json.dumps(payload, ensure_ascii=False),
            },
        ],
    )
    draft = _parse_json_model(raw, ProgressReportDraft)
    generation = {
        "agent": "progress_report_agent",
        "status": "completed",
        "config_source": "environment_chat_config",
        "provider": provider.provider,
        "model": provider.model,
        "base_host": urlparse(provider.base_url or "").hostname,
    }
    return draft, generation


def _parse_json_model(raw: str, schema: type[BaseModel]) -> Any:
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    start, end = cleaned.find("{"), cleaned.rfind("}")
    if start >= 0 and end > start:
        cleaned = cleaned[start : end + 1]
    try:
        return schema.model_validate_json(cleaned)
    except (ValidationError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Progress report model output failed validation: {exc}") from exc


def _restrict_evidence_refs(
    draft: ProgressReportDraft, allowed: set[str]
) -> ProgressReportDraft:
    cleaned = draft.model_copy(deep=True)
    for item in [
        *cleaned.completed_work,
        *cleaned.work_in_progress,
        *cleaned.discussion_insights,
        *cleaned.blockers,
        *cleaned.next_actions,
    ]:
        item.evidence_refs = list(
            dict.fromkeys(ref for ref in item.evidence_refs if ref in allowed)
        )
    return cleaned


def _render_progress_markdown(
    title: str,
    period: str,
    metrics: dict[str, int],
    draft: ProgressReportDraft,
) -> str:
    cycle = {"daily": "本日", "weekly": "本周", "monthly": "本月"}.get(
        period, "本周期"
    )
    lines = [
        f"# {title}",
        "",
        "## 一、执行摘要",
        draft.executive_summary.strip(),
        "",
        "## 二、进展判断",
        draft.progress_assessment.strip(),
        "",
        "## 三、已完成工作与产出",
    ]
    if draft.completed_work:
        for item in draft.completed_work:
            lines.extend(
                [
                    f"### {item.title}",
                    f"- 事实：{item.fact}",
                    f"- 意义：{item.significance}",
                    f"- 依据：{_refs(item.evidence_refs)}",
                ]
            )
    else:
        lines.append("- 无可核验完成项；系统运行记录未被当作科研产出。")

    lines.extend(["", "## 四、进行中工作"])
    if draft.work_in_progress:
        for item in draft.work_in_progress:
            lines.extend(
                [
                    f"### {item.title}",
                    f"- 当前状态：{item.fact}",
                    f"- 预期意义：{item.significance}",
                    f"- 依据：{_refs(item.evidence_refs)}",
                ]
            )
    else:
        lines.append("- 当前没有足够记录支持进行中事项判断。")

    lines.extend(["", "## 五、问题、阻塞与风险"])
    if draft.blockers:
        for item in draft.blockers:
            lines.extend(
                [
                    f"- **问题：** {item.issue}",
                    f"  - 影响：{item.impact}",
                    f"  - 处理建议：{item.proposed_resolution}",
                    f"  - 依据：{_refs(item.evidence_refs)}",
                ]
            )
    else:
        lines.append("- 记录中没有明确阻塞；这不等同于实际不存在阻塞。")
    lines.extend(f"- 风险：{risk}" for risk in draft.risks[:6])

    lines.extend(["", "## 六、讨论焦点与形成的判断"])
    if draft.discussion_insights:
        for item in draft.discussion_insights:
            lines.extend(
                [
                    f"- **{item.title}：** {item.fact}",
                    f"  - 科研含义：{item.significance}",
                    f"  - 依据：{_refs(item.evidence_refs)}",
                ]
            )
    else:
        lines.append("- 对话记录尚未形成可核验的研究判断。")

    lines.extend(["", f"## 七、{cycle}后续行动"])
    for index, item in enumerate(draft.next_actions, start=1):
        criteria = "；".join(item.acceptance_criteria)
        deadline = item.target_date or "待结合计划日期确认"
        lines.extend(
            [
                f"{index}. **[{item.priority.upper()}] {item.action}**",
                f"   - 原因：{item.rationale}",
                f"   - 交付物：{item.deliverable}",
                f"   - 验收标准：{criteria}",
                f"   - 目标时间：{deadline}",
                f"   - 依据：{_refs(item.evidence_refs)}",
            ]
        )

    lines.extend(
        [
            "",
            "## 八、量化记录",
            f"- 科研活动记录：{metrics['activity_events']} 条",
            f"- 有效对话：{metrics['dialogue_turns']} 条",
            f"- 完成计划：{metrics['completed_plans']} 项",
            f"- 开放计划：{metrics['pending_plans']} 项",
            f"- 已审核匹配导师：{metrics['matched_mentors']} 位",
            f"- 已记录论文阅读：{metrics['read_papers']} 项",
            "",
            "## 九、信息缺口与数据边界",
        ]
    )
    lines.extend(
        f"- {item}" for item in draft.missing_information[:8]
    )
    if not draft.missing_information:
        lines.append("- 未发现模型需要额外声明的信息缺口。")
    lines.append("- 报告只使用平台内已记录事实；未记录的线下进展不作推断。")
    return "\n".join(lines)


def _review_report(markdown: str, draft: ProgressReportDraft) -> list[str]:
    failed: list[str] = []
    if len(markdown) < 650:
        failed.append("report_too_short")
    if not draft.next_actions:
        failed.append("next_actions_missing")
    if any(not item.acceptance_criteria for item in draft.next_actions):
        failed.append("acceptance_criteria_missing")
    runtime_hits = sum(
        1 for line in markdown.splitlines() if _RUNTIME_LINE.match(line.lstrip("-#* "))
    )
    if runtime_hits >= 2:
        failed.append("runtime_log_leak")
    return failed


def _clean_chat_content(content: str) -> str:
    lines = [
        line.strip()
        for line in content.splitlines()
        if line.strip() and not _RUNTIME_LINE.match(line.strip())
    ]
    return "\n".join(lines)


def _compact_value(value: Any, depth: int = 0) -> Any:
    if depth >= 3:
        return str(value)[:240]
    if isinstance(value, dict):
        return {
            str(key): _compact_value(item, depth + 1)
            for key, item in list(value.items())[:16]
            if str(key) not in {"payload_json", "raw", "content_markdown"}
        }
    if isinstance(value, list):
        return [_compact_value(item, depth + 1) for item in value[:10]]
    if isinstance(value, str):
        return value[:600]
    return value


def _collect_evidence_refs(value: Any) -> list[str]:
    if isinstance(value, dict):
        own = value.get("evidence_refs")
        refs = [str(item) for item in own if str(item)] if isinstance(own, list) else []
        for item in value.values():
            refs.extend(_collect_evidence_refs(item))
        return list(dict.fromkeys(refs))
    if isinstance(value, list):
        refs: list[str] = []
        for item in value:
            refs.extend(_collect_evidence_refs(item))
        return list(dict.fromkeys(refs))
    return []


def _refs(values: list[str]) -> str:
    return "、".join(values) if values else "平台记录（无外部证据编号）"


def _persist_progress(
    session: Session,
    request: RunCreate,
    artifact: dict[str, Any],
    evidence_refs: list[str],
    *,
    status: str,
    review_status: str,
    run_id: int | None,
) -> RunCreated:
    output_json = {
        "review_status": review_status,
        "evidence_refs": evidence_refs,
        "artifact": artifact,
    }
    error_message = str(artifact.get("error") or "") or None
    repository = AgentRunRepository(session)
    if run_id is None:
        run = repository.create(
            WorkflowName.progress_report.value,
            status=status,
            input_json={
                "message": request.message,
                "metadata": {
                    "harness_skill_id": "progress_report",
                    "period_type": request.context.report_period or "weekly",
                },
            },
            output_json=output_json,
            error_message=error_message,
        )
    else:
        run = repository.update_status(
            run_id,
            status,
            output_json=output_json,
            error_message=error_message,
        )
    session.commit()
    return RunCreated(
        run_id=str(run.id),
        skill_id="progress_report",
        status=run.status,
        review_status=review_status,
        evidence_refs=evidence_refs,
        artifact=artifact,
    )


def _persist(
    session: Session,
    request: RunCreate,
    workflow: str,
    skill_id: str,
    artifact: dict[str, Any],
    evidence_refs: list[str],
) -> RunCreated:
    run = AgentRunRepository(session).create(
        workflow,
        status=RunStatus.succeeded.value,
        input_json={"message": request.message, "metadata": {"harness_skill_id": skill_id}},
        output_json={"review_status": "PASS", "evidence_refs": evidence_refs, "artifact": artifact},
    )
    session.commit()
    return RunCreated(
        run_id=str(run.id), skill_id=skill_id, status=run.status,
        review_status="PASS", evidence_refs=evidence_refs, artifact=artifact,
    )
